---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  restartPolicy: Always
  containers:
    - image: gcr.io/google_containers/busybox
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      name: busybox
      volumeMounts:
        - name: storage-volume
          mountPath: /data
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: storage-pvc
